<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Workout Garnet</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="/css/mdb.min.css" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="/css/authorization.css" rel="stylesheet">
</head>

<body>

<nav class="navbar-fixed-bottom">
    <div class="footer">
        <div class="d-flex footer btn-group btn-group-sm" role="group" aria-label="Basic example">
            <button type="button" class="btn footer btn-lg col-sm-2"><a href="/news">news</a></button>
            <button type="button" class="btn footer btn-lg col-sm-3"><a href="/training">train</a></button>
            <button type="button" class="btn footer btn-lg col-sm-2"><a href="/main"><img src="/img/home.png" alt="" class="img-fluid" style="height: 20px;"></a></button>
            <button type="button" class="btn footer btn-lg col-sm-3"><a href="/main">info</a></button>
            <button type="button" class="btn footer btn-lg col-sm-2"><a href="/user">user</a></button>
        </div>
    </div>
</nav>

<section class="form-dark">
    <div class="card card-image ">
        <div class="logo mt-4" align="center">
            <img src="/img/logo.png" alt="" class="img-fluid">
        </div>
        <div class="text-white py-2 px-5 z-depth-4">
            <div class="text-center">
                <h3 class="white-text mb-3 mt-4 font-weight-bold text-uppercase"><strong>404</strong></h3>
            </div>
        </div>
    </div>
</section>

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="/js/jquery-3.3.1.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="/js/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="/js/mdb.min.js"></script>
</body>

</html>
