<!DOCTYPE html>
<html lang="en">
<head>
  <title>Workout Garnet</title>
  <!--<meta charset="utf-8">-->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
  <link href="/css/bootstrap.min.css" rel="stylesheet">
  <link href="/css/mdb.min.css" rel="stylesheet">
  <link href="/css/style.css" rel="stylesheet">
</head>
<body>
<nav class="navbar-fixed-bottom">
  <div class="footer">   
     <div class="d-flex footer btn-group btn-group-sm" role="group" aria-label="Basic example">
        <button type="button" class="btn footer btn-lg col-sm-2"><a href="/news">news</a></button>
        <button type="button" class="btn footer btn-lg col-sm-3"><a href="/training">train</a></button>
        <button type="button" class="btn footer btn-lg col-sm-2"><a href="/main"><img src="/img/home.png" alt="" class="img-fluid" style="height: 20px;"></a></button>
        <button type="button" class="btn footer btn-lg col-sm-3"><a href="/main">info</a></button>
        <button type="button" class="btn footer btn-lg col-sm-2"><a href="/user">user</a></button>
    </div>
  </div>
</nav>

<nav class="navbar-fixed-top">
    <div class="top">
        <div class="d-flex btn-group btn-group-sm top" role="group" aria-label="Basic example">
            <div>
                <button type="button" class="btn top btn-group-sm d-flex nazad">
                    <span class="white-text name">Workout Garnet</span>
                </button>
            </div>
        </div>
    </div>
</nav>

<div class="container-fluid do">
      <!--<figure class="view mdb-lightbox">
        <a href="/search">
          <img alt="placeholder" src="https://mdbootstrap.com/img/Photos/Lightbox/Thumbnail/img%20(145).jpg" class="img-fluid">
          <div class="mask flex-center waves-effect waves-light rgba-teal-light">
            <p class="white-text font-weight-bold">Поиск</p>
          </div>
        </a>
      </figure>-->

      <figure class="view mdb-lightbox">
        <a href="/list/inventory">
          <img alt="picture" src="/img/oborydovanie.jpg" class="img-fluid" />
           <div class="mask flex-center waves-effect waves-light rgba-teal-light">
            <p class="white-text font-weight-bold">Оборудование</p>
          </div>
        </a>
      </figure>

      <figure class="view mdb-lightbox">
        <a href="/list/muscles">
          <img alt="picture" src="/img/muscles.jpg" class="img-fluid" />
           <div class="mask flex-center waves-effect waves-light rgba-teal-light">
            <p class="white-text font-weight-bold">Мышцы</p>
          </div>
        </a>
      </figure>

    <figure class="view mdb-lightbox">
        <a href="/list/user">
            <img alt="picture" src="/img/users.jpg" class="img-fluid" />
            <div class="mask flex-center waves-effect waves-light rgba-teal-light">
                <p class="white-text font-weight-bold">Пользователи</p>
            </div>
        </a>
    </figure>

      <figure class="view mdb-lightbox posle">
       <a href="/list/foreground">
         <img alt="picture" src="/img/ploschadka.jpg" class="img-fluid" />
          <div class="mask flex-center waves-effect waves-light rgba-teal-light">
           <p class="white-text font-weight-bold">Площадки</p>
         </div>
       </a>
     </figure>
    </div>

</body>
</html>